### PR TITLE
Add binder dir to run on mybinder.org

### PR DESCRIPTION
**Pull request by wenzeslaus**
* Adds binder directory with the config.
* Uses the releasebranch_8_0 branch.
* Puts source code and binaries in grass directory in home.
* No data download (some are in the repo).

Launch binder link which leads to assignment 2B part 1 notebook:

https://mybinder.org/v2/gh/wenzeslaus/GIS714-assignments/add-binder?labpath=Assignment2%2FGIS714_assignment2B-part1.ipynb

### CODE REVIEW

**Comment by chaedri** [comment]
I know this is still a draft but I went to test it in Binder anyways. Interestingly, I got the same error in the first cell that many students are getting (code below). Could this be a larger Mac/UNIX issue?

`Starting GRASS GIS...
WARNING: It appears that the X Windows system is not active.
A graphical based user interface is not supported.
(DISPLAY variable is not set.)
Switching to text based interface mode.
Cleaning up temporary files...
Traceback (most recent call last):
  File "/home/jovyan/.local/bin/grass", line 2741, in <module>
    main()
  File "/home/jovyan/.local/bin/grass", line 2721, in main
    gui_process.wait()
AttributeError: 'NoneType' object has no attribute 'wait'
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
/tmp/ipykernel_88/2654655743.py in <module>
     10 
     11 sys.path.append(
---> 12     subprocess.check_output([grass_call, "--config", "python_path"], text=True, shell=True).strip()
     13 )
     14 

/srv/conda/envs/notebook/lib/python3.7/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    409 
    410     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 411                **kwargs).stdout
    412 
    413 

/srv/conda/envs/notebook/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    510         if check and retcode:
    511             raise CalledProcessError(retcode, process.args,
--> 512                                      output=stdout, stderr=stderr)
    513     return CompletedProcess(process.args, retcode, stdout, stderr)
    514 

CalledProcessError: Command '['grass', '--config', 'python_path']' returned non-zero exit status 1.`

**Comment by wenzeslaus** [comment]
Whatever is the reason for this in the source code, it works as expected when you leave out `shell=True` in the subprocess call. It is not in the notebooks in GRASS repo. Perhaps you added that for Windows where it is necessary?

**Comment by wenzeslaus** [comment]
With `grass_call` set to `"grass"` most of the cells work right away. In 3C, the gs.create_location call requires runtime to be set up already, but that happens only with gj.init, so it fails. Perhaps something to resolve in next PR.

```
# Create new location for baranjahill
gs.create_location("../data", "baranjahill", filename="../data/tmp/elevations.prj")

# Start GRASS Session
gj.init("../data", "baranjahill", "PERMANENT")
```

**Comment by chaedri** [comment]
> Whatever is the reason for this in the source code, it works as expected when you leave out `shell=True` in the subprocess call. It is not in the notebooks in GRASS repo. Perhaps you added that for Windows where it is necessary?

Yes, I remember adding that for Windows. It's a pain how each OS needs a different launch command.

**Comment by chaedri** [comment]
I'll merge this PR then address the `shell=True` in another commit.

**Pull request merged**
