### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by epauluk92**

### CODE REVIEW

**Review by chaedri — CHANGES_REQUESTED** [review]
Well done opening up a PR! Go ahead and add the `print("intro")` line and I'll merge it.

**Comment by epauluk92** [comment]
Caitlin, can you explain how to do pull/push in a better way than manually editing/uploading each version? I'm still not quite sure how pull/push is supposed to work in this context. I am familiar with Desktop and the command line (sort of), but not sure that's what we're meant to be doing here.

**Comment by chaedri** [comment]
> Well done opening up a PR! Go ahead and add the `print("intro")` line and I'll merge it.

I realize in hindsight this was an unclear direction: instead of "intro", put your own introduction. There are a few examples that have been merged already and mine says "Howdy! I'm Caitlin, the TA for GIS714."

Then, I'll go ahead and merge it!

**Comment by epauluk92** [comment]
Caitlin, I'm still not 100% sure how this works or if this is correct. Trying my best, I think I did a new pull request.

**Review by chaedri — APPROVED** [review]
Thanks! This looks better.

**Comment by chaedri** [comment]
> Caitlin, I'm still not 100% sure how this works or if this is correct. Trying my best, I think I did a new pull request.

Still the same PR so you did it all correctly! Thanks for the changes. I will go ahead and merge.

**Pull request merged**
